### ISSUE TITLE
Document properties

### ISSUE THREAD

**Issue by craigpfeifer** [ivanhe/termolator#2]
The properties file contains the properties:

stopWordListName = data/CN.nw.wordlist.txt
endWordListName = data/CN.endlist.txt
forbiddenCharListName = data/CN.charlist.txt
stopThreshold = 50
forbiddenThreshold = 800
minAV = 5
minCount = 3
minDocumentCount = 5
terminologyThreshold = 0.6

Could you document what each parameter is? I think the first 3 are obvious, but the others could use some explanation.

Thanks!

**Comment by craigpfeifer** [comment]
Also, if there are other properties squirreled away somewhere that can affect the results, that would be useful as well!

**Comment by ivanhe** [comment]
I will document the parameters, but what matters most is using a Chinese word segmenter that works well on your data.

**Comment by craigpfeifer** [comment]
Agreed. Bad segmentation is impossible to recover from.

**Comment by ivanhe** [comment]
Updated README.md. Thank you!
